image: quay-its.epfl.ch/svc0176/hemmelig
version: nodemodules
app: paste
subdomain: paste
domain: fsd.epfl.ch
host: "{{ subdomain }}{% if openshift_env == 'test' %}-test{% endif %}.{{ domain }}"
url: "https://{{ host }}"
secrets: "{{ lookup('pipe', 'keybase fs read /keybase/team/epfl_sopec/paste/secrets.yml') | from_yaml }}"

postgres_cluster:
  name: postgres-cluster
