apiVersion: v1
kind: Secret
metadata:
  name: oslf-secrets
  labels:
    app.kubernetes.io/name: oslf
    app.kubernetes.io/part-of: sopec
type: Opaque
stringData:
  API_USERNAME: "{{ .global.api_username }}"
  API_PASSWORD: "{{ .global.api_password }}"
  API_URL: "{{ .global.api_url }}"
