apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: umami
  labels:
    app.kubernetes.io/name: umami
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: sopec
    app.kubernetes.io/managed-by: argocd
spec:
  cluster:
    name: postgres-cluster
  name: umami-db
  owner: umami-user
  passwordSecret:
    name: umami-db-credentials
