apiVersion: v1
kind: Secret
metadata:
  name: umami-db-credentials
  labels:
    app.kubernetes.io/name: umami
    app.kubernetes.io/part-of: sopec
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: umami-user
  password: "{{ .env.database.password }}"
  database: umami-db
---
apiVersion: v1
kind: Secret
metadata:
  name: umami-secrets
  labels:
    app.kubernetes.io/name: umami
    app.kubernetes.io/part-of: sopec
type: Opaque
stringData:
  APP_SECRET: "{{ .env.app_secret }}"
  DATABASE_URL: "postgresql://umami-user:{{ .env.database.password }}@postgres-cluster-rw:5432/umami-db"
  DATABASE_TYPE: postgres
  HOSTNAME: "0.0.0.0"
  PORT: "3000"
