- name: Create application secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app }}-secrets"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      stringData:
        APP_SECRET: "{{ secrets[openshift_env].app_secret }}"
        DATABASE_URL: "postgresql://{{ app }}-user:{{ secrets[openshift_env].database.password }}@postgres-cluster-rw:5432/{{ app }}-db"
        DATABASE_TYPE: "postgres"
