- name: common
  hosts: all
  roles:
  - role: roles/common
  tags:
  - common

- name: boardfsdash
  hosts: all
  roles:
  - role: roles/boardfsdash
  tags:
  - boardfsdash

- name: eeee
  hosts: all
  roles:
  - role: roles/eeee
  tags:
  - eeee

- name: gatus
  hosts: all
  roles:
  - role: roles/gatus
  tags:
  - gatus

- name: gotenberg
  hosts: all
  roles:
  - role: roles/gotenberg
  tags:
  - gotenberg

- name: grist
  hosts: all
  roles:
  - role: roles/grist
  tags:
  - grist

- name: jdt-manager
  hosts: all
  roles:
  - role: roles/jdt-manager
  tags:
  - jdt-manager

- name: n8n
  hosts: all
  roles:
  - role: roles/n8n
  tags:
  - n8n

- name: oslf
  hosts: all
  roles:
  - role: roles/oslf
  tags:
  - oslf

- name: Open WebUI (OWUI)
  hosts: all
  roles:
  - role: roles/owui
  tags:
  - owui

- name: paste
  hosts: all
  roles:
  - role: roles/paste
  tags:
  - paste

- name: plane
  hosts: all
  roles:
  - role: roles/plane
  tags:
  - plane

- name: umami
  hosts: all
  roles:
  - role: roles/umami
  tags:
  - umami

- name: uptime-kuma
  hosts: all
  roles:
  - role: roles/uptime-kuma
  tags:
  - uptime-kuma

- name: zipline
  hosts: all
  roles:
  - role: roles/zipline
  tags:
  - zipline

- name: rapport-de-stage
  hosts: all
  roles:
  - role: roles/rapport-de-stage
  tags:
  - rapport-de-stage
