apiVersion: v1
kind: Secret
metadata:
  name: boardfsdash-secrets
  labels:
    app.kubernetes.io/name: boardfsdash
    app.kubernetes.io/part-of: sopec
type: Opaque
stringData:
  AUTH_MICROSOFT_ENTRA_ID_ID: "{{ .env.auth.client_id }}"
  AUTH_MICROSOFT_ENTRA_ID_SECRET: "{{ .env.auth.client_secret }}"
  AUTH_MICROSOFT_ENTRA_ID_ISSUER: "{{ .env.auth.issuer_id }}"
  AUTH_EWS_CREDENTIALS_USERNAME: "{{ .env.api.username }}"
  AUTH_EWS_CREDENTIALS_PASSWORD: "{{ .env.api.password }}"
  AUTH_EWS_SERVICE_ENDPOINT: "{{ .env.api.endpoint }}"
  AUTH_SECRET: "{{ .env.secret_key }}"
  AUTH_URL: "https://dash{{ .suffix }}.fsd.epfl.ch"
