apiVersion: v1
kind: Secret
metadata:
  name: boardfsdash-secrets
  labels:
    app.kubernetes.io/name: boardfsdash
    app.kubernetes.io/part-of: sopec
type: Opaque
stringData:
  AUTH_MICROSOFT_ENTRA_ID_ID: "{{ .env.auth.client_id }}"
  AUTH_MICROSOFT_ENTRA_ID_SECRET: "{{ .env.auth.client_secret }}"
  AUTH_MICROSOFT_ENTRA_ID_ISSUER: "{{ .env.auth.issuer_id }}"
  TENANT_ID: "{{ .env.api_room.tenant_id }}"
  CLIENT_ID: "{{ .env.api_room.client_id }}"
  CLIENT_SECRET: "{{ .env.api_room.client_secret }}"
  AUTH_SECRET: "{{ .env.secret_key }}"
  AUTH_URL: "https://dash{{ .suffix }}.fsd.epfl.ch"
  GRAFANA_ENCRYPTION_KEY: "{{ .env.grafana_encryption_key }}"
