apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boardfsdash-data
  labels:
    app.kubernetes.io/name: boardfsdash
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: sopec
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sopec
