apiVersion: v1
kind: Secret
metadata:
  name: owui-db-credentials
  labels:
    app.kubernetes.io/name: owui
    app.kubernetes.io/part-of: sopec
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: owui-user
  password: "{{ .env.database.password }}"
  database: owui-db
---
apiVersion: v1
kind: Secret
metadata:
  name: owui-secrets
  labels:
    app.kubernetes.io/name: owui
    app.kubernetes.io/part-of: sopec
type: Opaque
stringData:
  WEBUI_URL: "https://owui{{ .suffix }}.fsd.epfl.ch"
  DATABASE_URL: "postgresql://owui-user:{{ .env.database.password }}@postgres-cluster-rw:5432/owui-db"
  DATABASE_TYPE: postgres
  ENABLE_OAUTH_SIGNUP: "true"
  ENABLE_OAUTH_PERSISTENT_CONFIG: "false"
  MICROSOFT_CLIENT_ID: "{{ .env.auth.client_id }}"
  MICROSOFT_CLIENT_SECRET: "{{ .env.auth.client_secret }}"
  MICROSOFT_CLIENT_TENANT_ID: "{{ .env.auth.tenant_id }}"
  OPENID_PROVIDER_URL: "https://login.microsoftonline.com/{{ .env.auth.tenant_id }}/v2.0/.well-known/openid-configuration"
  MICROSOFT_OAUTH_SCOPE: "openid email profile"
  MICROSOFT_REDIRECT_URI: "https://owui{{ .suffix }}.fsd.epfl.ch/oauth/microsoft/callback"
