apiVersion: v1
kind: Secret
metadata:
  name: authentik-db-credentials
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: sopec
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: authentik-user
  password: "{{ .env.database.password }}"
  database: authentik-db
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: sopec
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: "{{ .env.authentik.secret_key }}"
  AUTHENTIK_POSTGRESQL__HOST: postgres-cluster-rw
  AUTHENTIK_POSTGRESQL__NAME: authentik-db
  AUTHENTIK_POSTGRESQL__USER: authentik-user
  AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .env.database.password }}"
  AUTHENTIK_REDIS__HOST: authentik-redis
  AUTHENTIK_REDIS__PORT: "6379"
  AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
  AUTHENTIK_DISABLE_UPDATE_CHECK: "true"
