apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: grist
  labels:
    app.kubernetes.io/name: grist
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: sopec
spec:
  cluster:
    name: postgres-cluster
  name: grist-db
  owner: grist-user
