apiVersion: v1
kind: Secret
metadata:
  name: grist-db-credentials
  labels:
    app.kubernetes.io/name: grist
    app.kubernetes.io/part-of: sopec
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: grist-user
  password: "{{ .env.database.password }}"
  database: grist-db
---
apiVersion: v1
kind: Secret
metadata:
  name: grist-secrets
  labels:
    app.kubernetes.io/name: grist
    app.kubernetes.io/part-of: sopec
type: Opaque
stringData:
  APP_HOME_URL: "https://grist{{ .suffix }}.fsd.epfl.ch"
  APP_DOC_URL: "https://grist{{ .suffix }}.fsd.epfl.ch"
  TYPEORM_DATABASE: grist-db
  TYPEORM_HOST: postgres-cluster-rw
  TYPEORM_LOGGING: "false"
  TYPEORM_PORT: "5432"
  TYPEORM_TYPE: postgres
  TYPEORM_USERNAME: grist-user
  TYPEORM_PASSWORD: "{{ .env.database.password }}"
  REDIS_URL: redis://grist-redis/1
  GRIST_OIDC_IDP_ISSUER: "{{ .env.auth.issuer }}"
  GRIST_OIDC_IDP_CLIENT_ID: "{{ .env.auth.client_id }}"
  GRIST_OIDC_IDP_CLIENT_SECRET: "{{ .env.auth.client_secret }}"
  GRIST_OIDC_SP_IGNORE_EMAIL_VERIFIED: "true"
  GRIST_FORCE_LOGIN: "true"
  ALLOWED_WEBHOOK_DOMAINS: "*"
  GRIST_ALLOWED_ORIGINS: "*"
