apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grist-data
  labels:
    app.kubernetes.io/name: grist
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: sopec
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sopec
