- name: Create Migration Job
  kubernetes.core.k8s:
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: "{{ app }}-migrate"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: "{{ app }}"
          component: migrate
      spec:
        ttlSecondsAfterFinished: 300
        template:
          metadata:
            labels:
              app: "{{ app }}"
              component: migrate
          spec:
            restartPolicy: Never
            containers:
              - image: "{{ migrate_image }}:{{ version }}"
                imagePullPolicy: Always
                name: "{{ app }}-migrate"
                envFrom:
                  - secretRef:
                      name: "{{ app }}-secrets"
                resources:
                  requests:
                    cpu: 10m
                    memory: 128Mi
                  limits:
                    memory: 512Mi
            imagePullSecrets:
              - name: svc0176-pull-secret
