- name: Create application secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app }}-secrets"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      stringData:
        DB_HOST: "postgres-cluster-rw"
        DB_PORT: "5432"
        DB_NAME: "{{ app }}-db"
        DB_USER: "{{ app }}-user"
        DB_PASS: "{{ secrets[openshift_env].database.password }}"
        DB_TYPE: "postgres"
        SERVER_PORT: "8034"
        CLIENT_URL: "https://{{ subdomain }}{% if openshift_env == 'test' %}-test{% endif %}.{{ domain }}"
        MODE: "prod"
        TZ: "Europe/Zurich"