apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: svc0176p-isas-fsd

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: grist-redis
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 5m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 16Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 16Mi
  - target:
      kind: Deployment
      name: grist-web
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 2m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
