apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  labels:
    app.kubernetes.io/name: postgres-cluster
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: sopec
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  primaryUpdateStrategy: unsupervised
  backup:
    barmanObjectStore:
      data:
        compression: snappy
      wal:
        compression: snappy
        maxParallel: 8
      destinationPath: s3://PLACEHOLDER_S3_BUCKET/PLACEHOLDER_ENV
      endpointURL: PLACEHOLDER_S3_HOST
      s3Credentials:
        accessKeyId:
          name: s3-credentials
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: s3-credentials
          key: AWS_SECRET_ACCESS_KEY
  storage:
    size: 5Gi
    storageClass: sopec
  monitoring:
    enablePodMonitor: true
  enableSuperuserAccess: true
  env:
    - name: AWS_REQUEST_CHECKSUM_CALCULATION
      value: WHEN_REQUIRED
    - name: AWS_RESPONSE_CHECKSUM_VALIDATION
      value: WHEN_REQUIRED
  postgresql:
    parameters:
      max_connections: "600"
      max_slot_wal_keep_size: 3GB
      shared_buffers: 256MB
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      memory: 512Mi
  managed:
    roles:
      - connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        name: hedgedoc-user
        passwordSecret:
          name: hedgedoc-db-credentials
        superuser: false
      - connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        name: grist-user
        passwordSecret:
          name: grist-db-credentials
        superuser: false
      - connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        name: umami-user
        passwordSecret:
          name: umami-db-credentials
        superuser: false
      - connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        name: plane-user
        passwordSecret:
          name: plane-db-credentials
        superuser: false
      - connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        name: n8n-user
        passwordSecret:
          name: n8n-db-credentials
        superuser: false
      - connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        name: authentik-user
        passwordSecret:
          name: authentik-db-credentials
        superuser: false
      - connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        name: kuma-user
        passwordSecret:
          name: kuma-db-credentials
        superuser: false
      - connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        name: peekaping-user
        passwordSecret:
          name: peekaping-db-credentials
        superuser: false
      - connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        name: zipline-user
        passwordSecret:
          name: zipline-db-credentials
        superuser: false
      - connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        name: ctfd-user
        passwordSecret:
          name: ctfd-db-credentials
        superuser: false
      - connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        name: miamtrix-user
        passwordSecret:
          name: miamtrix-db-credentials
        superuser: false
      - connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        name: jdt-manager-user
        passwordSecret:
          name: jdt-manager-db-credentials
        superuser: false
