apiVersion: v1
kind: Secret
metadata:
  name: svc0176-pull-secret
  labels:
    app.kubernetes.io/part-of: sopec
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ .env.puller }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  labels:
    app.kubernetes.io/part-of: sopec
type: Opaque
stringData:
  AWS_BUCKET_NAME: "{{ .env.s3.name }}"
  AWS_BUCKET_HOST: "{{ .env.s3.host }}"
  AWS_ACCESS_KEY_ID: "{{ .env.s3.access_key_id }}"
  AWS_SECRET_ACCESS_KEY: "{{ .env.s3.access_key_secret }}"
