apiVersion: v1
kind: Secret
metadata:
  name: gatus-config
  labels:
    app.kubernetes.io/name: gatus
    app.kubernetes.io/part-of: sopec
stringData:
  config.yaml: |
    security:
      oidc:
        issuer-url: "{{ .env.oidc.issuer_url }}"
        redirect-url: "https://gatus{{ .suffix }}.fsd.epfl.ch/authorization-code/callback"
        client-id: "{{ .env.oidc.client_id }}"
        client-secret: "{{ .env.oidc.client_secret }}"
        scopes: ["openid"]
    endpoints:
      - name: SiDoc
        url: https://sidoc.epfl.ch
        interval: 60s
        conditions: ["[STATUS] == 200"]
      - name: WP-Veritas
        url: https://wp-veritas.epfl.ch
        interval: 60s
        conditions: ["[STATUS] == 200"]
      - name: Social
        url: https://social.epfl.ch
        interval: 60s
        conditions: ["[STATUS] == 200"]
      - name: WWW
        url: https://www.epfl.ch
        interval: 60s
        conditions: ["[STATUS] == 200"]
      - name: EEEE
        url: https://eeee.epfl.ch
        interval: 60s
        conditions: ["[STATUS] == 200"]
      - name: People
        url: https://people.epfl.ch
        interval: 60s
        conditions: ["[STATUS] == 200"]
      - name: Actu
        url: https://actu.epfl.ch
        interval: 60s
        conditions: ["[STATUS] == 200"]
      - name: Memento
        url: https://memento.epfl.ch
        interval: 60s
        conditions: ["[STATUS] == 200"]
      - name: Go
        url: https://go.epfl.ch
        interval: 60s
        conditions: ["[STATUS] == 200"]
