- name: Create serive account
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ app }}-srv-account"
        namespace: "{{ openshift_namespace }}"
      imagePullSecrets:
        - name: "svc0176-pull-secret"

- name: Create application secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app }}-secrets"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      stringData:
        SECRET_KEY: "{{ secrets[openshift_env].secret_key }}"
        REDIS_URL: "redis://{{ app }}-redis.{{ openshift_namespace }}:6379/"
        DATABASE_URL: "postgresql://{{ app }}-user:{{ secrets[openshift_env].database.password }}@{{ postgres_cluster.name }}-rw:5432/{{ app }}-db"
        AMQP_URL: "amqp://{{ app }}:{{ secrets[openshift_env].rabbitmq.password }}@{{ app }}-rabbitmq.{{ openshift_namespace }}:5672/"

- name: Create Doc store secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app }}-doc-store-secrets"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      stringData:
        FILE_SIZE_LIMIT: "5242880"
        AWS_S3_BUCKET_NAME: "uploads"
        USE_MINIO: "1"
        MINIO_ROOT_USER: "{{ app }}"
        MINIO_ROOT_PASSWORD: "{{ secrets[openshift_env].s3.password }}"
        AWS_ACCESS_KEY_ID: "{{ app }}"
        AWS_SECRET_ACCESS_KEY: "{{ secrets[openshift_env].s3.password }}"
        AWS_S3_ENDPOINT_URL: "http://{{ app }}-minio.{{ openshift_namespace }}:9000"

- name: Create config map for environment variables
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: "{{ openshift_namespace }}"
        name: "{{ app }}-vars"
      data:
        SENTRY_DSN: "{{ secrets[openshift_env].sentry.dsn | default('') }}"
        SENTRY_ENVIRONMENT: "{{ openshift_env | default('') }}"
        DEBUG: "0"
        DOCKERIZED: "1"
        GUNICORN_WORKERS: "1"
        MINIO_ENDPOINT_SSL: "0"
        API_KEY_RATE_LIMIT: "60/minute"
        WEB_URL: "http://{{ subdomain }}{% if openshift_env == 'test' %}-test{% endif %}.{{ domain }}"
        CORS_ALLOWED_ORIGINS: "http://{{ subdomain }}{% if openshift_env == 'test' %}-test{% endif %}.{{ domain }},https://{{ subdomain }}{% if openshift_env == 'test' %}-test{% endif %}.{{ domain }}"
