- name: Create application secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app }}-secrets"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      stringData:
        DATABASE_URL: "postgresql://{{ app }}-user:{{ secrets[openshift_env].database.password }}@{{ postgres_cluster.host }}:5432/{{ app }}-db"
        AUTH_SECRET: "{{ secrets[openshift_env].auth.secret }}"
        AUTH_URL: "https://{{ subdomain }}{% if openshift_env == 'test' %}-test{% endif %}.{{ domain }}"
        ENTRA_ID: "{{ secrets[openshift_env].auth.entra_id }}"
        ENTRA_SECRET: "{{ secrets[openshift_env].auth.entra_secret }}"
        ENTRA_ISSUER: "{{ secrets[openshift_env].auth.entra_issuer }}"
        MAIL_HOST: "{{ secrets[openshift_env].mail.host }}"
        MAIL_USER: "{{ secrets[openshift_env].mail.user }}"
        MAIL_PASSWORD: "{{ secrets[openshift_env].mail.password }}"
