- name: Create Deployment
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ app }}-bot"
        namespace: "{{ openshift_namespace }}"
      spec:
        replicas: 1
        strategy:
          type: Recreate
        selector:
          matchLabels:
            app: "{{ app }}"
            component: bot
        template:
          metadata:
            labels:
              app: "{{ app }}"
              component: bot
          spec:
            volumes:
              - name: bot-data
                persistentVolumeClaim:
                  claimName: "{{ app }}-data"
            containers:
              - image: "{{ image }}:{{ version }}"
                imagePullPolicy: Always
                name: "{{ app }}"
                envFrom:
                  - secretRef:
                      name: "{{ app }}-secrets"
                volumeMounts:
                  - name: bot-data
                    mountPath: /data
                resources:
                  requests:
                    cpu: 10m
                    memory: 150Mi
                  limits:
                    memory: 350Mi
            imagePullSecrets:
              - name: svc0176-pull-secret

- name: Create persistent Volume
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ app }}-data"
        namespace: "{{ openshift_namespace }}"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
