- name: Create application secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app }}-secrets"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      stringData:
        URI_API: "{{ secrets[openshift_env].api.url }}"
        API_PASSWORD: "{{ secrets[openshift_env].api.password }}"
        API_USERNAME: "{{ secrets[openshift_env].api.username }}"
        URL_SERVER_MATRIX: "{{ secrets[openshift_env].matrix.server_url }}"
        USERNAME_BOT: "{{ secrets[openshift_env].matrix.username }}"
        PASSWORD_BOT: "{{ secrets[openshift_env].matrix.password }}"
        DATABASE_URL: "postgresql_//{{ app }}-user:{{ secrets[openshift_env].database.password }}@{{ postgres_cluster.host }}:5432/{{ app }}-db"
