apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - database.yaml
  - configmap.yaml
  - redis.yaml
  - rabbitmq.yaml
  - minio.yaml
  - api.yaml
  - web.yaml
  - worker.yaml
  - admin.yaml
  - space.yaml
  - live.yaml
  - routes.yaml
  - jobs.yaml
