apiVersion: v1
kind: Secret
metadata:
  name: plane-db-credentials
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/part-of: sopec
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: plane-user
  password: "{{ .env.database.password }}"
  database: plane-db
---
apiVersion: v1
kind: Secret
metadata:
  name: plane-secrets
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/part-of: sopec
type: Opaque
stringData:
  SECRET_KEY: "{{ .env.secret_key }}"
  DATABASE_URL: "postgresql://plane-user:{{ .env.database.password }}@postgres-cluster-rw:5432/plane-db"
  AMQP_URL: "amqp://plane:{{ .env.rabbitmq.password }}@plane-rabbitmq:5672/"
---
apiVersion: v1
kind: Secret
metadata:
  name: plane-doc-store-secrets
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/part-of: sopec
type: Opaque
stringData:
  FILE_SIZE_LIMIT: "5242880"
  AWS_S3_BUCKET_NAME: uploads
  USE_MINIO: "1"
  MINIO_ROOT_USER: plane
  MINIO_ROOT_PASSWORD: "{{ .env.s3.password }}"
  AWS_ACCESS_KEY_ID: plane
  AWS_SECRET_ACCESS_KEY: "{{ .env.s3.password }}"
  AWS_S3_ENDPOINT_URL: http://plane-minio:9000
---
apiVersion: v1
kind: Secret
metadata:
  name: plane-rabbitmq-secrets
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/part-of: sopec
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: plane
  RABBITMQ_DEFAULT_PASS: "{{ .env.rabbitmq.password }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: plane-live-secrets
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/part-of: sopec
type: Opaque
stringData:
  REDIS_URL: redis://plane-redis:6379/
