apiVersion: v1
kind: ServiceAccount
metadata:
  name: plane-srv-account
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: sopec
imagePullSecrets:
  - name: svc0176-pull-secret
