apiVersion: v1
kind: Service
metadata:
  name: plane-web
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: sopec
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: plane
    app.kubernetes.io/component: web
  ports:
    - name: web
      port: 3000
      protocol: TCP
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plane-web
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: sopec
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plane
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plane
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: sopec
    spec:
      serviceAccountName: plane-srv-account
      containers:
        - name: web
          image: quay-its.epfl.ch/svc0176/plane-frontend:stable
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 1000Mi
            limits:
              cpu: 500m
              memory: 1000Mi
