- name: Create boardfsdash service
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ app }}"
        namespace: "{{ openshift_namespace }}"
      spec:
        selector:
          app: "{{ app }}"
        ports:
          - name: "{{ app }}-svc-port"
            protocol: TCP
            port: 80
            targetPort: 3000

- name: Create boardfsdash Route
  kubernetes.core.k8s:
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ app }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: "{{ app }}"
          route: public-cf
      spec:
        host: "{{ subdomain }}{% if openshift_env == 'test' %}-test{% endif %}.{{ domain }}"
        to:
          kind: Service
          name: "{{ app }}"
        port:
          targetPort: "{{ app }}-svc-port"
        tls:
          termination: edge
          insecureEdgeTerminationPolicy: Redirect

- name: Create Deployment
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ app }}"
        namespace: "{{ openshift_namespace }}"
      spec:
        replicas: 1
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 1
        selector:
          matchLabels:
            app: "{{ app }}"
        template:
          metadata:
            labels:
              app: "{{ app }}"
          spec:
            containers:
              - image: "{{ image }}:{{ version }}"
                imagePullPolicy: Always
                name: "{{ app }}"
                ports:
                  - containerPort: 3000
                envFrom:
                  - secretRef:
                      name: "{{ app }}-secrets"
                volumeMounts:
                  - name: boardfsdash-data
                    mountPath: /app/data
                resources:
                  requests:
                    cpu: 50m
                    memory: 128Mi
                  limits:
                    cpu: 200m
                    memory: 512Mi
                readinessProbe:
                  tcpSocket:
                    port: 3000
                  initialDelaySeconds: 5
                  timeoutSeconds: 3
                livenessProbe:
                  tcpSocket:
                    port: 3000
                  initialDelaySeconds: 5
                  timeoutSeconds: 3
            imagePullSecrets:
              - name: svc0176-pull-secret
            volumes:
              - name: boardfsdash-data
                persistentVolumeClaim:
                  claimName: "{{ app }}-data"