- name: Create application secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app }}-secrets"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      stringData:
        # https://docs.openwebui.com/reference/env-configuration/

        WEBUI_URL: "{{ url }}"

        ## Database
        DATABASE_URL: "postgresql://{{ app }}-user:{{ secrets[openshift_env].database.password }}@postgres-cluster-rw:5432/{{ app }}-db"
        DATABASE_TYPE: "postgres"

        # Entra ID (OIDC)
        ENABLE_OAUTH_SIGNUP: "true"
        ENABLE_OAUTH_PERSISTENT_CONFIG: "false"
        MICROSOFT_CLIENT_ID: "{{ secrets[openshift_env].auth.client_id }}"
        MICROSOFT_CLIENT_SECRET: "{{ secrets[openshift_env].auth.client_secret }}"
        MICROSOFT_CLIENT_TENANT_ID: "{{ secrets[openshift_env].auth.tenant_id }}"
        OPENID_PROVIDER_URL: "https://login.microsoftonline.com/{{ secrets[openshift_env].auth.tenant_id }}/v2.0/.well-known/openid-configuration"
        MICROSOFT_OAUTH_SCOPE: "openid email profile"
        MICROSOFT_REDIRECT_URI: "{{ url }}/oauth/microsoft/callback"

        # Plugins
        # ENABLE_WEB_SEARCH: True
        # SEARXNG_QUERY_URL: http://searxng:8080/search?q=<query>&format=json
