- name: NfsSubdirExternalProvisioner's
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: nfs.epfl.ch/v1alpha1
      kind: NfsSubdirProvisioner
      metadata:
        name: "sopec"
        namespace: "{{ openshift_namespace }}"
      spec:
        nfs:
          server: "{{ secrets[openshift_env].nfs.server }}"
          path: "{{ secrets[openshift_env].nfs.path }}"
        storageClass:
          defaultClass: false
          name: "sopec"
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 256Mi
