apiVersion: v1
kind: Secret
metadata:
  name: jdt-manager-db-credentials
  labels:
    app.kubernetes.io/name: jdt-manager
    app.kubernetes.io/part-of: sopec
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: jdt-manager-user
  password: "{{ .env.database.password }}"
  database: jdt-manager-db
---
apiVersion: v1
kind: Secret
metadata:
  name: jdt-manager-secrets
  labels:
    app.kubernetes.io/name: jdt-manager
    app.kubernetes.io/part-of: sopec
type: Opaque
stringData:
  DATABASE_URL: "postgresql://jdt-manager-user:{{ .env.database.password }}@postgres-cluster-rw:5432/jdt-manager-db"
  AUTH_SECRET: "{{ .env.auth.secret }}"
  AUTH_URL: "https://jdt{{ .suffix }}.fsd.epfl.ch"
  ENTRA_ID: "{{ .env.auth.entra_id }}"
  ENTRA_SECRET: "{{ .env.auth.entra_secret }}"
  ENTRA_ISSUER: "{{ .env.auth.entra_issuer }}"
  MAIL_HOST: "{{ .env.mail.host }}"
  MAIL_USER: "{{ .env.mail.user }}"
  MAIL_PASSWORD: "{{ .env.mail.password }}"
