apiVersion: v1
kind: Secret
metadata:
  name: n8n-db-credentials
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/part-of: sopec
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: n8n-user
  password: "{{ .env.database.password }}"
  database: n8n-db
---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/part-of: sopec
type: Opaque
stringData:
  DB_TYPE: postgresdb
  DB_POSTGRESDB_HOST: postgres-cluster-rw
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: n8n-db
  DB_POSTGRESDB_USER: n8n-user
  DB_POSTGRESDB_PASSWORD: "{{ .env.database.password }}"
  N8N_HOST: "n8n{{ .suffix }}.fsd.epfl.ch"
  N8N_PORT: "5678"
  N8N_ENCRYPTION_KEY: "{{ .env.key }}"
  N8N_PROTOCOL: https
  WEBHOOK_URL: "https://n8n{{ .suffix }}.fsd.epfl.ch/"
  N8N_USER_FOLDER: /home/node/.n8n
  GENERIC_TIMEZONE: Europe/Paris
  TZ: Europe/Paris
  N8N_LOG_LEVEL: info
