- name: Create application secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app }}-secrets"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      stringData:
        AUTHENTIK_SECRET_KEY: "{{ secrets[openshift_env].authentik.secret_key }}"
        AUTHENTIK_POSTGRESQL__HOST: "postgres-cluster-rw"
        AUTHENTIK_POSTGRESQL__NAME: "{{ app }}-db"
        AUTHENTIK_POSTGRESQL__USER: "{{ app }}-user"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ secrets[openshift_env].database.password }}"
        AUTHENTIK_REDIS__HOST: "{{ app }}-redis"
        AUTHENTIK_REDIS__PORT: "6379"
        AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
        AUTHENTIK_DISABLE_UPDATE_CHECK: "true"