- name: Create application secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app }}-secrets"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      stringData:
        AUTH_MICROSOFT_ENTRA_ID_ID: "{{ secrets[openshift_env].auth.client_id }}"
        AUTH_MICROSOFT_ENTRA_ID_SECRET: "{{ secrets[openshift_env].auth.client_secret }}"
        AUTH_MICROSOFT_ENTRA_ID_TENANT_ID: "{{ secrets[openshift_env].auth.tenant_id }}"
        AUTH_EWS_CREDENTIALS_USERNAME: "{{ secrets[openshift_env].api.username }}"
        AUTH_EWS_CREDENTIALS_PASSWORD: "{{ secrets[openshift_env].api.password }}"
        AUTH_EWS_SERVICE_ENDPOINT: "{{ secrets[openshift_env].api.endpoint }}"
        AUTH_SECRET: "{{ secrets[openshift_env].secret_key }}"
        AUTH_URL: "https://{{ subdomain }}{% if openshift_env == 'test' %}-test{% endif %}.{{ domain }}"