secrets: "{{ lookup('pipe', 'keybase fs read /keybase/team/epfl_sopec/common/secrets.yml') | from_yaml }}"

postgres_users:
  - hedgedoc
  - grist
  - umami
  - plane
  - n8n
  - authentik
  - kuma
  - peekaping
