secrets: "{{ lookup('pipe', 'keybase fs read /keybase/team/epfl_sopec/common/secrets.yml') | from_yaml }}"

postgres_users:
  - outlinewiki
  - hedgedoc
  - rallly
  - grist

postgres_roles: "{{ postgres_users | map('regex_replace', '^(.*)$', {'name': '\\1-user', 'ensure': 'present', 'login': true, 'superuser': false, 'passwordSecret': {'name': '\\1-db-credentials'}}) | list }}"
