apiVersion: v1
kind: Secret
metadata:
  name: miamtrix-db-credentials
  labels:
    app.kubernetes.io/name: miamtrix
    app.kubernetes.io/part-of: sopec
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: miamtrix-user
  password: "{{ .env.database.password }}"
  database: miamtrix-db
---
apiVersion: v1
kind: Secret
metadata:
  name: miamtrix-secrets
  labels:
    app.kubernetes.io/name: miamtrix
    app.kubernetes.io/part-of: sopec
type: Opaque
stringData:
  URI_API: "{{ .env.api.url }}"
  API_PASSWORD: "{{ .env.api.password }}"
  API_USERNAME: "{{ .env.api.username }}"
  URL_SERVER_MATRIX: "{{ .env.matrix.server_url }}"
  USERNAME_BOT: "{{ .env.matrix.username }}"
  PASSWORD_BOT: "{{ .env.matrix.password }}"
  DATABASE_URL: "postgresql://miamtrix-user:{{ .env.database.password }}@postgres-cluster-rw:5432/miamtrix-db"
